site_name: bitlayer-l2 docs
site_url: https://bitlayer-org.github.io/docs
site_author: bitlayer-l2
repo_url: https://github.com/bitlayer-org/docs
docs_dir: docs/
theme:
    name: material
    favicon: images/FA_Bitlayer_Logo.jpg
    logo: images/FA_Bitlayer_Logo.jpg
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - javascript
        - shell
nav:
    - About bitlayer-l2: index.md
    - Tutorials: tutorial.md
    - Main:
      - Compile and Run: dev/install.md
      - Deployment: dev/deploy.md
      - Testnet: testnet.md
      - JSON RPC: dev/json-rpc.md
    - FAQ: faq.md

